version: '3'
services:
  unity_webgl_server:
    image: nginx:alpine
    volumes:
      - ./unity_webgl_server:/usr/share/nginx/html
      - ./unity_webgl_server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  arm_controller:
    build:
      context: ./arm_controller
    ports:
      - "65433:65433" # websocket
      - "8500:8500" # controller 
    volumes:
      - ./arm_controller/src:/app/src
      - ./arm_controller/pyproject.toml:/app/pyproject.toml
      - ./arm_controller/pdm.lock:/app/pdm.lock
    depends_on:
      - arm_twin

  arm_twin:
    build:
      context: ./arm_twin
    volumes:
      - ./arm_twin/main.cpp:/app/main.cpp
      - ./arm_twin/CMakeLists.txt:/app/CMakeLists.txt
      - ./arm_twin/components:/app/components