version: '3.8'
services:
  unity_webgl_server:
    image: nginx:alpine
    volumes:
      - ./unity_webgl_server:/usr/share/nginx/html
      - ./unity_webgl_server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  controller:
    build:
      context: ./controller
    ports:
      - "$CONTROLLER_WEBSOCKET_PORT:$CONTROLLER_WEBSOCKET_PORT" # websocket
      - "$CONTROLLER_SERVER_PORT:$CONTROLLER_SERVER_PORT" # controller 
    volumes:
      - ./controller/src:/app/src
      - ./controller/pyproject.toml:/app/pyproject.toml
      - ./controller/pdm.lock:/app/pdm.lock
    depends_on:
      - arm_twin
    environment:
      - CONTROLLER_SERVER_HOST
      - CONTROLLER_SERVER_PORT

  firmware:
    build:
      context: ./firmware
    volumes:
      - ./firmware/main.cpp:/app/main.cpp
      - ./firmware/CMakeLists.txt:/app/CMakeLists.txt
      - ./firmware/components:/app/components
    environment:
      - WIFI_SSID
      - WIFI_PASSWORD
      - CONTROLLER_SERVER_HOST
      - CONTROLLER_SERVER_PORT
      - RUN_TWIN_ON_HOST