version: '3.8'
services:

  # ---- ARM SIMULATION
  unity_webgl_server:
    image: nginx:alpine
    volumes:
      - ./unity_arm_simulation/unity_webgl_server:/usr/share/nginx/html
      - ./unity_arm_simulation/unity_webgl_server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $ARM_SIMULATION_PORT:80

  # ---- CONTROLLER PYTHON PACKAGE
  controller:
    pid: "host"
    build:
      context: ./controller
    ports:
      - "$CONTROLLER_WEBSOCKET_PORT:$CONTROLLER_WEBSOCKET_PORT" # websocket
      - "$CONTROLLER_SERVER_PORT:$CONTROLLER_SERVER_PORT" # controller 
    volumes:
      - ./controller/src:/app/src
      - ./controller/pyproject.toml:/app/pyproject.toml
      - ./controller/pdm.lock:/app/pdm.lock
    environment:
      - PDM_PUBLISH_USERNAME=$CONTROLLER_PDM_PUBLISH_USERNAME
      - PDM_PUBLISH_PASSWORD=$CONTROLLER_PDM_PUBLISH_PASSWORD

# ---- BACKEND (HTTP API)
  backend:
    build: 
      context: "./backend"
      dockerfile: "Dockerfile"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./controller:/app/controller
    ports:
      - "$CONTROLLER_WEBSOCKET_PORT:$CONTROLLER_WEBSOCKET_PORT" # websocket
      - "$CONTROLLER_SERVER_PORT:$CONTROLLER_SERVER_PORT" # controller 
      - "$BACKEND_HTTP_PORT:$BACKEND_HTTP_PORT" # fastapi
    environment:
      - BACKEND_HTTP_PORT
      - CONTROLLER_WEBSOCKET_PORT
      - CONTROLLER_SERVER_PORT

# ---- FIRMWARE (Linux runtime)
  firmware:
    pid: "host"
    build:
      context: ./firmware
      dockerfile: Dockerfile
    volumes:
      - ./firmware/main:/app/main
      - ./firmware/CMakeLists.txt:/app/CMakeLists.txt
      - ./firmware/components:/app/components
    environment:
      - ESP_WIFI_SSID
      - ESP_WIFI_PASSWORD
      - ESP_CONTROLLER_SERVER_HOST
      - ESP_CONTROLLER_SERVER_PORT

# ---- FRONTEND (Next.js)
  frontend:
      build: ./frontend
      volumes:
        - ./frontend/src:/app/src
        - ./frontend/package.json:/app/package.json
        - ./frontend/package-lock.json:/app/package-lock.json
        - ./frontend/tailwind.config.js:/app/tailwind.config.js
        - ./frontend/postcss.config.js:/app/postcss.config.js
      ports:
        - "3000:3000"
      environment:
        - NEXT_PUBLIC_BACKEND_URL
        - NEXT_PUBLIC_ARM_SIMULATION_WEBSOCKET_PORT
        - NEXT_PUBLIC_ARM_SIMULATION_WEBSOCKET_HOST
        - NEXT_PUBLIC_ARM_SIMULATION_URL
