
[Controller_PDM]
publish_username = "__token__"
publish_password = "tokenhere!"
override_version = "None"
increment_version = false

[DockerComposeDebug]
compose_docker_cli_build = 1
docker_buildkit = 1
