[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "alberto-abarzua", email = "aabarzua@palvi.cl"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
