title = "Robot arm configuration"
[joint_configuration]
    speed_rad_per_s = 0.5
    steps_per_rev_motor_axis = 200 # Microstepping
    homing_direction = 1 # 1 or -1
    max_angle_rad = 2.0 * pi # Max max_angle_rad
    min_angle_rad = -2.0 * pi # Min max_angle_rad
    # Settings can be overwritten for each joint

[[joints]
    name = "joint_1"
    homing_direction = 1 # 1 or -1
    convertion_rate_axis_joint = 1.0 # Gear ratio
    home_offset_rad = 0.0 # Offset from home position
    [joints.driver]
        type = "stepper"
        dir_pin = 20
        step_pin = 21
    # [joints.driver]
    #     type = "servo"
    #     pin = 20


[[joints]]
    name = "joint_2"
    homing_direction = 1 # 1 or -1
    convertion_rate_axis_joint = 1.0 # Gear ratio
    home_offset_rad = 0.0 # Offset from home position
    [joints.driver]
        type = "stepper"
        dir_pin = 20
        step_pin = 21
        
[[joints]]
    name = "joint_3"
    homing_direction = 1 # 1 or -1
    convertion_rate_axis_joint = 1.0 # Gear ratio
    home_offset_rad = 0.0 # Offset from home position
    [joints.driver]
        type = "stepper"
        dir_pin = 20
        step_pin = 21

[[joints]]
    name = "joint_4"
    homing_direction = 1 # 1 or -1
    convertion_rate_axis_joint = 1.0 # Gear ratio
    home_offset_rad = 0.0 # Offset from home position
    [joints.driver]
        type = "stepper"
        dir_pin = 20
        step_pin = 21

[[joints]]
    name = "joint_5"
    homing_direction = 1 # 1 or -1
    convertion_rate_axis_joint = 1.0 # Gear ratio
    home_offset_rad = 0.0 # Offset from home position
    [joints.driver]
        type = "stepper"
        dir_pin = 20
        step_pin = 21

[[joints]]
    name = "joint_6"
    homing_direction = 1 # 1 or -1
    convertion_rate_axis_joint = 1.0 # Gear ratio
    home_offset_rad = 0.0 # Offset from home position
    [joints.driver]
        type = "stepper"
        dir_pin = 20
        step_pin = 21

