version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./site:/var/www/html
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./site:/var/www/html # used to serve the challenge
    entrypoint: /bin/sh -c
    command: >
      'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'


