version: '3.8'
services:
  esp_idf:
    build:
      context: ../firmware
      dockerfile: Dockerfile.espidf

    
    image: "uintuser/ribot-espidf-firmware"
    network_mode: host
    volumes:
      - ../firmware/main:/app/main
      - ../firmware/CMakeLists.txt:/app/CMakeLists.txt
      - ../firmware/sdkconfig.defaults:/app/sdkconfig.defaults
      - ../firmware/components:/app/components
    environment:
      - ESP_WIFI_SSID
      - ESP_WIFI_PASSWORD
      - ESP_CONTROLLER_SERVER_HOST
      - ESP_CONTROLLER_SERVER_PORT
      - ESP_FLASH_PORT
      - VERBOSE
