version: "3.8"
services:
  frontend:
    build: ../frontend
    image: "uintuser/ribot-frontend"
    stop_grace_period: 5s
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/package.json:/app/package.json
      - ../frontend/package-lock.json:/app/package-lock.json
      - ../frontend/tailwind.config.js:/app/tailwind.config.js
      - ../frontend/components.json:/app/components.json
      - ../frontend/postcss.config.js:/app/postcss.config.js
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL
      - VITE_ARM_SIMULATION_WEBSOCKET_PORT
      - VITE_ARM_SIMULATION_WEBSOCKET_HOST
      - VITE_ARM_SIMULATION_URL
