version: '3.8'
services:
  frontend:
      build: ../frontend
      volumes:
        - ../frontend/src:/app/src
        - ../frontend/package.json:/app/package.json
        - ../frontend/package-lock.json:/app/package-lock.json
        - ../frontend/tailwind.config.js:/app/tailwind.config.js
        - ../frontend/postcss.config.js:/app/postcss.config.js
      ports:
        - "3000:3000"
      environment:
        - NEXT_PUBLIC_BACKEND_URL
        - NEXT_PUBLIC_ARM_SIMULATION_WEBSOCKET_PORT
        - NEXT_PUBLIC_ARM_SIMULATION_WEBSOCKET_HOST
        - NEXT_PUBLIC_ARM_SIMULATION_URL
