version: "3.8"
services:
  backend:
    build:
      context: "../instanciator/"
      dockerfile: "Dockerfile"
    image: "uintuser/ribot-instanciator"
    volumes:
      - ../instanciator/src:/app/src
      - ../instanciator/pyproject.toml:/app/pyproject.toml
      - ../instanciator/pdm.lock:/app/pdm.lock
    ports:
      - "$INSTANCIATOR_HTTP_PORT:$INSTANCIATOR_HTTP_PORT" # fastapi
    environment:
      - BACKEND_HTTP_PORT
      - CONTROLLER_WEBSOCKET_PORT
      - BACKEND_UPDATE_RIBOT_CONTROLLER
      - CONTROLLER_SERVER_PORT

volumes:
  pdm_cache:
