version: '3.8'
services:
  # ---- ARM SIMULATION
  unity_webgl_server:
    image: nginx:alpine
    volumes:
      - ../unity_arm_simulation/unity_webgl_server:/usr/share/nginx/html
      - ../unity_arm_simulation/unity_webgl_server/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $ARM_SIMULATION_PORT:80