
name: Backend Arm Ci

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-lint:
    runs-on: ubuntu-latest
    environment: general
    env:
      ESP_CONTROLLER_SERVER_PORT: ${{ vars.ESP_CONTROLLER_SERVER_PORT }}
      ESP_CONTROLLER_SERVER_HOST: ${{ vars.ESP_CONTROLLER_SERVER_HOST }}
      ESP_WIFI_SSID: ${{ vars.ESP_WIFI_SSID }}
      ESP_WIFI_PASSWORD: ${{ vars.ESP_WIFI_PASSWORD }}
      CONTROLLER_WEBSOCKET_PORT: ${{ vars.CONTROLLER_WEBSOCKET_PORT }}
      CONTROLLER_SERVER_PORT: ${{ vars.CONTROLLER_SERVER_PORT }}
      BACKEND_HTTP_PORT: ${{ vars.BACKEND_HTTP_PORT }}
      NEXT_PUBLIC_BACKEND_URL: ${{ vars.NEXT_PUBLIC_BACKEND_URL }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set Env File
        run: printenv | grep -v "^\(PWD\|SHLVL\|HOME\)" > .env

      - name: Install toml
        run: pip install toml

      - name: Build backend container
        run: ./ribot.py build --container backend --no-editable

      - name: Lint Backend
        run: ./ribot.py lint --container backend

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend Container
        if: github.ref == 'refs/heads/main'
        run: ./ribot.py docker-compose --container backend --op push

      - name: Stop and remove containers
        if: always()
        run: ./ribot.py down --container backend
    
         
